-- MySQL Script generated by MySQL Workbench
-- Sat May  6 03:07:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(65) NOT NULL,
  `primeiro_nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`login`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`bibliotecario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bibliotecario` (
  `cpf_bibli` VARCHAR(11) NOT NULL,
  `status` TINYINT NULL DEFAULT NULL,
  `usuario_login` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario_login`),
  CONSTRAINT `fk_bibliotecario_usuario1`
    FOREIGN KEY (`usuario_login`)
    REFERENCES `mydb`.`usuario` (`login`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`obra` (
  `primeiro_nome_autor` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `titulo_obra` VARCHAR(150) NOT NULL,
  `id_obra` INT NOT NULL AUTO_INCREMENT,
  `bibliotecario_usuario_login` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_obra`),
  INDEX `fk_obra_bibliotecario1_idx` (`bibliotecario_usuario_login` ASC) VISIBLE,
  CONSTRAINT `fk_obra_bibliotecario1`
    FOREIGN KEY (`bibliotecario_usuario_login`)
    REFERENCES `mydb`.`bibliotecario` (`usuario_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`e_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`e_book` (
  `ide_book` INT NOT NULL AUTO_INCREMENT,
  `isbn` VARCHAR(45) NULL DEFAULT NULL,
  `dcu` VARCHAR(45) NULL DEFAULT NULL,
  `url` VARCHAR(45) NOT NULL,
  `obra_id_obra` INT NOT NULL,
  PRIMARY KEY (`ide_book`),
  INDEX `fk_e_book_obra1_idx` (`obra_id_obra` ASC) VISIBLE,
  CONSTRAINT `fk_e_book_obra1`
    FOREIGN KEY (`obra_id_obra`)
    REFERENCES `mydb`.`obra` (`id_obra`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`acessa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`acessa` (
  `data_acesso` DATETIME NOT NULL,
  `usuario_login` VARCHAR(45) NOT NULL,
  `e_book_ide_book` INT NOT NULL,
  INDEX `fk_acessa_usuario1_idx` (`usuario_login` ASC) VISIBLE,
  INDEX `fk_acessa_e_book1_idx` (`e_book_ide_book` ASC) VISIBLE,
  CONSTRAINT `fk_acessa_e_book1`
    FOREIGN KEY (`e_book_ide_book`)
    REFERENCES `mydb`.`e_book` (`ide_book`),
  CONSTRAINT `fk_acessa_usuario1`
    FOREIGN KEY (`usuario_login`)
    REFERENCES `mydb`.`usuario` (`login`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livro` (
  `isbn` VARCHAR(45) NOT NULL,
  `edicao` VARCHAR(45) NOT NULL,
  `quantidade_exemplares` INT NOT NULL,
  `num_chamada` VARCHAR(45) NOT NULL,
  `cdu` VARCHAR(10) NULL DEFAULT NULL,
  `obra_id_obra` INT NOT NULL,
  PRIMARY KEY (`isbn`),
  INDEX `fk_livro_obra1_idx` (`obra_id_obra` ASC) VISIBLE,
  CONSTRAINT `fk_livro_obra1`
    FOREIGN KEY (`obra_id_obra`)
    REFERENCES `mydb`.`obra` (`id_obra`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`exemplar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exemplar` (
  `idexemplar` INT NOT NULL AUTO_INCREMENT,
  `flag_emprestimo` TINYINT NOT NULL,
  `estado_conservacao` VARCHAR(45) NULL DEFAULT NULL,
  `livro_isbn` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idexemplar`),
  INDEX `fk_exemplar_livro1_idx` (`livro_isbn` ASC) VISIBLE,
  CONSTRAINT `fk_exemplar_livro1`
    FOREIGN KEY (`livro_isbn`)
    REFERENCES `mydb`.`livro` (`isbn`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emprestimo` (
  `idemprestimo` INT NOT NULL AUTO_INCREMENT,
  `usuario_login` VARCHAR(45) NOT NULL,
  `exemplar_idexemplar` INT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_prevista_devolucao` DATE NOT NULL,
  `quantidade_renovacoes` INT NOT NULL,
  `data_devolucao` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idemprestimo`),
  INDEX `fk_emprestimo_usuario1_idx` (`usuario_login` ASC) VISIBLE,
  INDEX `fk_emprestimo_exemplar1_idx` (`exemplar_idexemplar` ASC) VISIBLE,
  CONSTRAINT `fk_emprestimo_exemplar1`
    FOREIGN KEY (`exemplar_idexemplar`)
    REFERENCES `mydb`.`exemplar` (`idexemplar`),
  CONSTRAINT `fk_emprestimo_usuario1`
    FOREIGN KEY (`usuario_login`)
    REFERENCES `mydb`.`usuario` (`login`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`estudante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estudante` (
  `estudante_mat` VARCHAR(12) NOT NULL,
  `cpf_estu` VARCHAR(11) NOT NULL,
  `status` TINYINT NULL DEFAULT NULL,
  `usuario_login` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario_login`),
  CONSTRAINT `fk_estudante_usuario1`
    FOREIGN KEY (`usuario_login`)
    REFERENCES `mydb`.`usuario` (`login`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`multa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`multa` (
  `pago` INT NOT NULL,
  `localizacao` VARCHAR(45) NULL DEFAULT NULL,
  `valor` INT NULL DEFAULT NULL,
  `emprestimo_idemprestimo` INT NOT NULL,
  PRIMARY KEY (`emprestimo_idemprestimo`),
  CONSTRAINT `fk_multa_emprestimo1`
    FOREIGN KEY (`emprestimo_idemprestimo`)
    REFERENCES `mydb`.`emprestimo` (`idemprestimo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor` (
  `professor_mat` VARCHAR(12) NOT NULL,
  `cpf_prof` VARCHAR(11) NOT NULL,
  `status` TINYINT NULL DEFAULT NULL,
  `usuario_login` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario_login`),
  CONSTRAINT `fk_professor_usuario1`
    FOREIGN KEY (`usuario_login`)
    REFERENCES `mydb`.`usuario` (`login`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `mat_professor` VARCHAR(12) NULL,
  `data_pedido` DATE NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `titulo_livro` VARCHAR(150) NOT NULL,
  `edicao` VARCHAR(45) NOT NULL,
  `professor_usuario_login` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_pedido_professor1_idx` (`professor_usuario_login` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_professor1`
    FOREIGN KEY (`professor_usuario_login`)
    REFERENCES `mydb`.`professor` (`usuario_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO usuario (login, senha, primeiro_nome, sobrenome) VALUES ("Professor 01", "abc123", "Prof", "01");
INSERT INTO usuario (login, senha, primeiro_nome, sobrenome) VALUES ("Professor 02", "abc123", "Prof", "02");
INSERT INTO usuario (login, senha, primeiro_nome, sobrenome) VALUES ("Professor 03", "abc123", "Prof", "03");
INSERT INTO usuario (login, senha, primeiro_nome, sobrenome) VALUES ("Bibliotecario 01", "abc123", "Bibli", "01");
INSERT INTO professor (professor_mat, cpf_prof, status, usuario_login) VALUES ("000000000001", "00000000001", 1, "Professor 01");
INSERT INTO professor (professor_mat, cpf_prof, status, usuario_login) VALUES ("000000000002", "00000000002", 1, "Professor 02");
INSERT INTO professor (professor_mat, cpf_prof, status, usuario_login) VALUES ("000000000003", "00000000003", 1, "Professor 03");
INSERT INTO bibliotecario (cpf_bibli, status, usuario_login) VALUES ("00000000001", 1, "Bibliotecario 01");
INSERT INTO pedido (mat_professor, data_pedido, status, titulo_livro, edicao, professor_usuario_login) VALUES ("000000000001", "2023-05-05", 1, "Introdução à Programação com Python: Algoritmos e Lógica de Programação Para Iniciantes", "3ª edição", "Professor 01");
INSERT INTO pedido (mat_professor, data_pedido, status, titulo_livro, edicao, professor_usuario_login) VALUES ("000000000001", "2023-05-05", 1, "Introdução à Linguagem SQL: Abordagem Prática Para Iniciantes", "1ª edição", "Professor 01");
INSERT INTO pedido (mat_professor, data_pedido, status, titulo_livro, edicao, professor_usuario_login) VALUES ("000000000001", "2023-05-05", 1, "Estruturas de Dados e Algoritmos com JavaScript: Escreva um Código JavaScript Complexo e Eficaz Usando a Mais Recente ECMAScript", "2ª edição", "Professor 02");
INSERT INTO obra (primeiro_nome_autor, sobrenome, titulo_obra, bibliotecario_usuario_login) VALUES ("Aditya", "Bhargava", "Entendendo Algoritmos: Um Guia Ilustrado Para Programadores e Outros Curiosos","Bibliotecario 01");
INSERT INTO obra (primeiro_nome_autor, sobrenome, titulo_obra, bibliotecario_usuario_login) VALUES ("Thomas", "Cormen", "Algoritmos - Teoria e Prática","Bibliotecario 01");
INSERT INTO livro (isbn, edicao, quantidade_exemplares, num_chamada, obra_id_obra) VALUES ("978-8575225639", "1º edição", 7, "111.111", 1);
INSERT INTO livro (isbn, edicao, quantidade_exemplares, num_chamada, cdu, obra_id_obra) VALUES ("978-8535236996", "3º edição", 10, "111.111", "004.4", 2);
